"""FastAPI wrapper exposing the A2UI agent over AG-UI's SSE protocol.

The frontend (a2ui_ui) speaks to this exclusively via @ag-ui/client's
HttpAgent at POST /agui. An Okta-validating gateway forwards a trusted
X-Employee-Id header; middleware reads it into a per-request contextvar
so the MCP tool wrapper can scope every query to that user.

Run with:
    uvicorn server:app --host 0.0.0.0 --port 8004
"""
from __future__ import annotations

from contextlib import asynccontextmanager

from ag_ui_langgraph import LangGraphAgent, add_langgraph_fastapi_endpoint
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.base import BaseHTTPMiddleware

from agent import build_agent
from identity import EMPLOYEE_ID_HEADER, set_current_employee_id

_agent = None


class EmployeeIdentityMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        set_current_employee_id(request.headers.get(EMPLOYEE_ID_HEADER))
        return await call_next(request)


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _agent
    _agent = await build_agent()
    add_langgraph_fastapi_endpoint(
        app,
        LangGraphAgent(
            name="a2ui_vulnerability_agent",
            description=(
                "A2UI Vulnerability Assistant - natural-language vulnerability "
                "search whose on-screen UI is generated by the LLM as an "
                "a2ui.org component tree and rendered by @a2ui/react."
            ),
            graph=_agent,
        ),
        path="/agui",
    )
    yield


app = FastAPI(title="A2UI Vulnerability Agent", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)
app.add_middleware(EmployeeIdentityMiddleware)


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}
