// A small badge conveying whether a visualization's data is TRUSTED
// (bound by reference to verbatim MCP tool output) or AI-generated (the
// LLM supplied the numbers because no data reference fit). Trusted
// visuals get a shield; untrusted ones get a muted "AI-generated" tag so
// the absence of the trust mark is explicit, never ambiguous.
export function TrustBadge({ trusted }: { trusted: boolean | undefined }) {
  if (trusted) {
    return (
      <span className="a2ui-trust a2ui-trust-verified" title="Bound to verified source data">
        <span className="a2ui-trust-icon" aria-hidden>
          🛡
        </span>
        Trusted data
      </span>
    );
  }
  return (
    <span className="a2ui-trust a2ui-trust-ai" title="Generated by the AI, not bound to source data">
      AI-generated
    </span>
  );
}
